version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mentored_net
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    logging:
      driver: none
  kafka:
    image: 'bitnami/kafka:3.1.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - mentored_net
    volumes:
      - kafka-data:/bitnami/kafka
    logging:
      driver: none
  redis:
    image: 'redis:7.0.0'
    restart: 'always'
    ports:
      - '6379:6379'
    networks:
      - mentored_net
    logging:
      driver: none
  mentoring:
    build: './'
    image: elevate/mentoring:2.6
    volumes:
      - ./src/:/var/src
    ports:
      - '3000:3000'
    command: ['nodemon', 'app.js']
    environment:
      - KAFKA_URL=kafka:9092
      - USER_SERVICE_HOST=http://user:3001
      - DEV_DATABASE_URL=postgres://postgres:postgres@citus_master:5432/mentoring-local
      - REDIS_HOST=redis://redis:6379
      - SCHEDULER_SERVICE_HOST=http://scheduler:4000
    depends_on:
      - kafka
    networks:
      - mentored_net
  user:
    build: '../user/'
    image: elevate/user:2.6
    volumes:
      - ../user/src/:/var/src
    ports:
      - '3001:3001'
    command: ['nodemon', 'app.js']
    environment:
      - KAFKA_URL=kafka:9092
      - REDIS_HOST=redis://redis:6379
      - DEV_DATABASE_URL=postgres://postgres:postgres@citus_master:5432/user-local
    depends_on:
      - kafka
      - redis
    networks:
      - mentored_net
  notification:
    build: '../notification/'
    image: elevate/notification:2.6
    volumes:
      - ../notification/src/:/var/src
    ports:
      - '3002:3002'
    command: ['nodemon', 'app.js']
    environment:
      - KAFKA_HOST=kafka:9092
      - DEV_DATABASE_URL=postgres://postgres:postgres@citus_master:5432/notification-local
    depends_on:
      - kafka
    networks:
      - mentored_net
  scheduler:
    build: '../scheduler/'
    image: elevate/scheduler:2.6
    volumes:
      - ../scheduler/src/:/var/src
    ports:
      - '4000:4000'
    command: ['nodemon', 'app.js']
    environment:
      - KAFKA_URL=kafka:9092
    depends_on:
      - kafka
      - redis
    networks:
      - mentored_net
  interface:
    build: '../interface-service/'
    image: elevate/interface:2.6
    volumes:
      - ../interface-service/src/:/var/src
    ports:
      - '3567:3567'
    command: ['nodemon', 'app.js']
    networks:
      - mentored_net
  citus:
    image: citusdata/citus:11.2.0
    container_name: 'citus_master'
    ports:
      - 5434:5432
    environment: &AUTH
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      PGUSER: '${POSTGRES_USER:-postgres}'
      PGPASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: 'user-local'
      POSTGRES_HOST_AUTH_METHOD: '${POSTGRES_HOST_AUTH_METHOD:-trust}'
      POSTGRES_LOG_STATEMENT: 'all'
    networks:
      - mentored_net
  pgadmin:
    image: dpage/pgadmin4
    container_name: elevate-pgadmin
    restart: always
    ports:
      - '5600:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@shikshalokam.org
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - mentored_net
    logging:
      driver: none
networks:
  mentored_net:
    external: false
volumes:
  zookeeper-data:
  kafka-data:
  redis_data:
  healthcheck-volume:
